#########################################################
#
#   IPHONE/ICLOUD SELECTION AUTOMATIONS
#
#########################################################
- alias: Set Gary iPhone Interval
  id: set_gary_iphone_interval
  trigger:
    - platform: state
      entity_id: input_select.icloud3_set_interval
  action:
    - service: device_tracker.icloud3_set_interval
      data_template:
        account_name: gary_icloud
        device_name: gary_iphone
        interval: "{{ states.input_select.icloud3_set_interval.state }}"

- alias: iCloud Command
  id: icloud3_command
  trigger:
    - platform: state
      entity_id: input_select.icloud3_commands
  action:
    - service: device_tracker.icloud3_update
      data_template:
        account_name: gary_icloud
        command: "{{ states.input_select.icloud3_commands.state }}"        

- alias: iCloud Debug Command
  id: icloud3_debug_command
  trigger:
    - platform: state
      entity_id: input_select.icloud3_debug_commands
  action:
    - service: device_tracker.icloud3_update
      data_template:
        account_name: gary_icloud
        command: "{{ states.input_select.icloud3_debug_commands.state }}"